name: Hello World
on: push
jobs:
  build:
    name: Docker

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore
      run: dotnet restore 