name: Hello World
on: push
jobs:
  build:
    name: Docker

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore
      run: dotnet restore SimpleWebHalloWorld.csproj
    - name: Build
      run: dotnet build --no-restore --verbosity normal SimpleWebHalloWorld.csproj

    login:
      runs-on: ubuntu-latest
      
        - name: Login To Github 
          uses: docker/login-action/v1
          with: 
            registry: ghcr.io
            username: ${{ github.KevinKallin }}
            password: ${{ github.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 }}
        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2.7.0
          with: 
            push: true
            context: ${ {env.working-directory} }/PROJECT_DIR
            
