on: push
jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    env: 
      working-directory: .
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1.10.0
      with:
         registry: ghcr.io
         username: ${ { github.actor } };
         password: ${ { secrets.GITHUB_PAT } }
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2.7.0
      with:
        push: true
        context: ${ {env.working-directory} }/PROJECT_DIR
        tags: |
          ghcr.io/kevinkallin/simplewebhalloworld:latest
          ghcr.io/kevinkallin/simplewebhalloworld:${ { github.run_number } }





# ===--- Gitub CI Pipeline ---===

# name: Hello World
# on: push
# jobs:
#   build:
#     name: Docker

#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: 5.0.x
    
#     - name: Restore
#       run: dotnet restore SimpleWebHalloWorld.csproj
#     - name: Build
#       run: dotnet build --no-restore --verbosity normal SimpleWebHalloWorld.csproj

    