on: push
jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up VM
      uses: docker/setup-qemu-action@v1
    - name: Set up docker image
      uses: docker/setup-buildx-action@v1
    - name: Login to Github container registry
      uses: docker/login-action@v1
      with: 
         registry: ghcr.io
         username: ${{ github.actor }};
         password: ${{ secrets.MY_PAT }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ${ {env.working-directory} }
        tags: |
          ghcr.io/kevinkallin/simplewebhalloworld:master





# ===--- Gitub CI Pipeline ---===

# name: Hello World
# on: push
# jobs:
#   build:
#     name: Docker

#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: 5.0.x
    
#     - name: Restore
#       run: dotnet restore SimpleWebHalloWorld.csproj
#     - name: Build
#       run: dotnet build --no-restore --verbosity normal SimpleWebHalloWorld.csproj

    