name: Build Docker

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Set up for QEMU
        uses: docker/setup-qemu-action@v1 # QEMU emulerar ett operativsystem 
      - name: Set up for Docker Build 
        uses: docker/setup-buildx-action@v1 # Bygger en docker image
      - name: Login to GitHub Container Registry 
        uses: docker/login-action@v1 # Authentiserar mot Docker hub
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }} # Github "hemlighet" för mitt användarnamn
          password: ${{ secrets.PASSWORD }} # Github "hemlighet" för mitt lösenord
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2 # Bygger docker image och "pushar" den till ett privat register
        with:
          push: true
          context: ${{ env.working-directory }}
          tags: | # Namnet på min image i docker
            ghcr.io/kevinkallin/test:latest  


# === TEST === 

# name: Docker 

# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Docker meta
#         id: docker_meta
#         uses: crazy-max/ghaction-docker-meta@v1
#         with:
#           images: ghcr.io/kevinkallin/test
#           tag-sha: true
#           tag-edge: false
#           tag-latest: true

#       - name: Setup QEMU
#         uses: docker/setup-qemu-action@v1

#       - name: Setup Docker buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Login to GHCR
#         uses: docker/login-action@v1
#         with: 
#           registry: ghcr.io
#           username: ${{ secrets.USERNAME }}
#           password: ${{ secrets.PASSWORD }}

#       - name: Build image
#         uses: docker/build-push-action@v2
#         with:
#           tags: ${{ steps.docker_meta.outputs.tags }}
#           file: ./Dockerfile
        
#       - name: Push image
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           tags: ${{ steps.docker_meta.outputs.tags }}
#           file: ./Dockerfile



# ===--- My own  ---===

# name: Docker image Pipeline
# on: push
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up vm

#       uses: docker/setup-qemu-action@v1
#     - name: Set up docker image
#       uses: docker/setup-buildx-action@v1

#     - name: Login to Github container registry
#       uses: docker/login-action@v1
#       with: 
#         registry: ghcr.io
#         username: ${{ github.actor }};
#         password: ${{ secrets.CR_PAT }}
   
#     - name: Build the image
#       id: docker_build
#       uses: docker/build-push-action@v2
#       with:
#         tags: ${{ steps.docker_meta.outputs.tags }}
#         file: ./Dockerfile

#     - name: Push the image
#       uses: docker/build-push-action@v2
#       with: 
#         push: true
#         tags: ${{ steps.docker_meta.outputs.tags }}
#         file: ./Dockerfile




# ===--- Gitub CI Pipeline ---===

# name: Hello World
# on: push
# jobs:
#   build:
#     name: Docker

#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: 5.0.x
    
#     - name: Restore
#       run: dotnet restore SimpleWebHalloWorld.csproj
#     - name: Build
#       run: dotnet build --no-restore --verbosity normal SimpleWebHalloWorld.csproj

    